version: '3'
services:
  postgres:
    image: postgres:13
    container_name: auth_postgres
    ports:
    - 5432:5432
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=auth
    volumes:
      - pg_data_users:/var/lib/postgresql/data
    networks:
      - auth

  redis:
    image: redis:6-buster
    container_name: auth_redis
    ports:
    - 6379:6379
    volumes:
      - rediis_data_users:/data
    networks:
      - auth

volumes:
  pg_data_users:
  rediis_data_users:

networks:
  auth:
    driver: bridge
