version: '3'
services:
  auth:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: auth_auth
    ports:
    - 5000:5000
    env_file:
      - ./.env
    networks:
      - auth
    depends_on:
      - postgres
      - redis
